const SELECT_CATEGORY = 'SELECT_CATEGORY';
const SEARCH_NEWS = 'SEARCH_NEWS';
const REQUEST_CATEGORY = 'REQUEST_CATEGORY';
const RECEIVE_NEWS = 'RECEIVE_NEWS';

export default { SEARCH_NEWS, SELECT_CATEGORY, REQUEST_CATEGORY, RECEIVE_NEWS };